services:
  - type: web
    name: shree-raga-swaad-ghar
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
