services:
  - type: web
    name: shree-raaga-swaad-ghar
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true

